/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package barberbros;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class History extends javax.swing.JFrame {
    Connection con;
    Statement st;
    ResultSet rs;

    /**
     * Creates new form History
     */
    public History() {
        initComponents();
        data();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBooking = new javax.swing.JTable();
        SidePanel = new javax.swing.JPanel();
        Homemenu = new javax.swing.JLabel();
        HistoryMenu = new javax.swing.JLabel();
        StylistMenu = new javax.swing.JLabel();
        BookingMenu = new javax.swing.JLabel();
        TreatmentMenu = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        UserButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(230, 213, 184));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("History");

        tabelBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Tanggal", "Jam", "Stylist", "Total Cost", "No Hp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelBooking.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelBooking);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(jLabel1))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );

        SidePanel.setBackground(new java.awt.Color(240, 165, 0));

        Homemenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Homemenu.setForeground(java.awt.Color.white);
        Homemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Homemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_home_page_100px.png"))); // NOI18N
        Homemenu.setText("Home");
        Homemenu.setToolTipText("");
        Homemenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Homemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomemenuMouseClicked(evt);
            }
        });

        HistoryMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HistoryMenu.setForeground(java.awt.Color.white);
        HistoryMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HistoryMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_order_history_80px.png"))); // NOI18N
        HistoryMenu.setText("History");
        HistoryMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HistoryMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryMenuMouseClicked(evt);
            }
        });

        StylistMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        StylistMenu.setForeground(java.awt.Color.white);
        StylistMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StylistMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_beard_50px.png"))); // NOI18N
        StylistMenu.setText("Stylist");
        StylistMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StylistMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StylistMenuMouseClicked(evt);
            }
        });

        BookingMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BookingMenu.setForeground(java.awt.Color.white);
        BookingMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookingMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_ticket_50px.png"))); // NOI18N
        BookingMenu.setText("Booking");
        BookingMenu.setToolTipText("");
        BookingMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookingMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMenuMouseClicked(evt);
            }
        });

        TreatmentMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TreatmentMenu.setForeground(java.awt.Color.white);
        TreatmentMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TreatmentMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cleansing_50px.png"))); // NOI18N
        TreatmentMenu.setText("Treatment");
        TreatmentMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TreatmentMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreatmentMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addComponent(HistoryMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanelLayout.createSequentialGroup()
                        .addComponent(BookingMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(TreatmentMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Homemenu, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(StylistMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Homemenu)
                .addGap(42, 42, 42)
                .addComponent(BookingMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(StylistMenu)
                .addGap(46, 46, 46)
                .addComponent(TreatmentMenu)
                .addGap(56, 56, 56)
                .addComponent(HistoryMenu)
                .addGap(26, 26, 26))
        );

        headerPanel.setBackground(new java.awt.Color(27, 26, 23));

        UserButton.setForeground(java.awt.Color.white);
        UserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_account_30px.png"))); // NOI18N
        UserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_barbershop_100px.png"))); // NOI18N
        jLabel2.setText("BarberBross");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LogOutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Logout_50px.png"))); // NOI18N
        LogOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 872, Short.MAX_VALUE)
                .addComponent(LogOutButton)
                .addGap(18, 18, 18)
                .addComponent(UserButton)
                .addGap(27, 27, 27))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LogOutButton)
                            .addComponent(UserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomemenuMouseClicked
        // TODO add your handling code here:
        Home homePage = new Home();
        homePage.show();
        
        dispose();
    }//GEN-LAST:event_HomemenuMouseClicked

    private void HistoryMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMenuMouseClicked
        // TODO add your handling code here:
        History historyPage = new History();
        historyPage.show();
        
        dispose();
    }//GEN-LAST:event_HistoryMenuMouseClicked

    private void StylistMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StylistMenuMouseClicked
        // TODO add your handling code here:
        InterfaceStylist stylistPage = new InterfaceStylist();
        stylistPage.show();
        
        dispose();
    }//GEN-LAST:event_StylistMenuMouseClicked

    private void BookingMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMenuMouseClicked
        // TODO add your handling code here:
        Interface bookingPage = new Interface();
        bookingPage.show();
        
        dispose();
    }//GEN-LAST:event_BookingMenuMouseClicked

    private void TreatmentMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreatmentMenuMouseClicked
        // TODO add your handling code here:
        Treatment treatmentPage = new Treatment();
        treatmentPage.show();

        dispose();
    }//GEN-LAST:event_TreatmentMenuMouseClicked

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You've been log out!");
        
        Login loginPage = new Login();
        loginPage.show();
        
        dispose();
    }//GEN-LAST:event_LogOutButtonMouseClicked

     private void data(){
     try{
            con = Config.configDB();
            String sql = "SELECT * FROM booking";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                DefaultTableModel model = (DefaultTableModel) tabelBooking.getModel();
                Object[] row = new Object[13];
                row[0] = rs.getString("Booking_Name");
                row[1] = rs.getString("Booking_Date");
                row[2] = rs.getString("Booking_Time");
                row[3] = rs.getString("Booking_Stylish");
                row[4] = rs.getString("Booking_TotalCost");
                row[5] = rs.getString("Booking_PhoneNumber");
                
                model.addRow(row);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookingMenu;
    private javax.swing.JLabel HistoryMenu;
    private javax.swing.JLabel Homemenu;
    private javax.swing.JLabel LogOutButton;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel StylistMenu;
    private javax.swing.JLabel TreatmentMenu;
    private javax.swing.JLabel UserButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tabelBooking;
    // End of variables declaration//GEN-END:variables
}
