/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package barberbros;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author akbar_t6fy92r
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceStylist
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        footerPanel = new javax.swing.JPanel();
        StylistMenu = new javax.swing.JLabel();
        HistoryMenu = new javax.swing.JLabel();
        TreatmentMenu = new javax.swing.JLabel();
        BookingMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        UserButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        footerPanel.setBackground(new java.awt.Color(240, 165, 0));

        StylistMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        StylistMenu.setForeground(java.awt.Color.white);
        StylistMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StylistMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_beard_50px.png"))); // NOI18N
        StylistMenu.setText("Stylist");
        StylistMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StylistMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StylistMenuMouseClicked(evt);
            }
        });

        HistoryMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HistoryMenu.setForeground(java.awt.Color.white);
        HistoryMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HistoryMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_order_history_80px.png"))); // NOI18N
        HistoryMenu.setText("History");
        HistoryMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HistoryMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryMenuMouseClicked(evt);
            }
        });

        TreatmentMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TreatmentMenu.setForeground(java.awt.Color.white);
        TreatmentMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TreatmentMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cleansing_50px.png"))); // NOI18N
        TreatmentMenu.setText("Treatment");
        TreatmentMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TreatmentMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreatmentMenuMouseClicked(evt);
            }
        });

        BookingMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BookingMenu.setForeground(java.awt.Color.white);
        BookingMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookingMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_ticket_50px.png"))); // NOI18N
        BookingMenu.setText("Booking");
        BookingMenu.setToolTipText("");
        BookingMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookingMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMenuMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose Option :");

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookingMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TreatmentMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HistoryMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StylistMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(177, 177, 177))
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(503, 503, 503)
                .addComponent(jLabel1)
                .addContainerGap(506, Short.MAX_VALUE))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StylistMenu)
                    .addComponent(BookingMenu))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HistoryMenu)
                    .addComponent(TreatmentMenu))
                .addGap(35, 35, 35))
        );

        headerPanel.setBackground(new java.awt.Color(27, 26, 23));

        UserButton.setForeground(java.awt.Color.white);
        UserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_account_30px.png"))); // NOI18N
        UserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_barbershop_100px.png"))); // NOI18N
        jLabel2.setText("BarberBross");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LogOutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Logout_50px.png"))); // NOI18N
        LogOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutButton)
                .addGap(18, 18, 18)
                .addComponent(UserButton)
                .addGap(27, 27, 27))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LogOutButton)
                            .addComponent(UserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 75)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 201, 1));
        jLabel4.setText("BarberBross");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 110, 600, 90);

        jLabel5.setFont(new java.awt.Font("Perpetua", 1, 35)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome To");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 70, 200, 40);

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Getting Started By Choosing any Option Below");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 230, 390, 30);

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Let's Set Up a Hair Treatment Booking Schedule For our Customer");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 200, 550, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("__________________________________________________________________________");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 170, 600, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home1.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1232, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HistoryMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMenuMouseClicked
        // TODO add your handling code here:
        History historyPage = new History();
        historyPage.show();
        
        dispose();
    }//GEN-LAST:event_HistoryMenuMouseClicked

    private void TreatmentMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreatmentMenuMouseClicked
        // TODO add your handling code here:
        Treatment treatmentPage = new Treatment();
        treatmentPage.show();
        
        dispose();
    }//GEN-LAST:event_TreatmentMenuMouseClicked

    private void StylistMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StylistMenuMouseClicked
        // TODO add your handling code here:
        InterfaceStylist stylistPage = new InterfaceStylist();
        stylistPage.show();
        
        dispose();
    }//GEN-LAST:event_StylistMenuMouseClicked

    private void BookingMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMenuMouseClicked
        // TODO add your handling code here:
        Interface bookingPage = new Interface();
        bookingPage.show();
        
        dispose();
    }//GEN-LAST:event_BookingMenuMouseClicked

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You've been log out!");
        
        Login loginPage = new Login();
        loginPage.show();
        
        dispose();
    }//GEN-LAST:event_LogOutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookingMenu;
    private javax.swing.JLabel HistoryMenu;
    private javax.swing.JLabel LogOutButton;
    private javax.swing.JLabel StylistMenu;
    private javax.swing.JLabel TreatmentMenu;
    private javax.swing.JLabel UserButton;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
