/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package barberbros;

import javax.swing.JOptionPane;

/**
 *
 * @author akbar_t6fy92r
 */
public class InterfaceStylist extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceStylist
     */
    public InterfaceStylist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel1 = new javax.swing.JPanel();
        Homemenu1 = new javax.swing.JLabel();
        HistoryMenu1 = new javax.swing.JLabel();
        TreatmentMenu1 = new javax.swing.JLabel();
        StylistMenu1 = new javax.swing.JLabel();
        BookingMenu1 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        UserButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SidePanel1.setBackground(new java.awt.Color(240, 165, 0));

        Homemenu1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Homemenu1.setForeground(java.awt.Color.white);
        Homemenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Homemenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_home_page_100px.png"))); // NOI18N
        Homemenu1.setText("Home");
        Homemenu1.setToolTipText("");
        Homemenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Homemenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Homemenu1MouseClicked(evt);
            }
        });

        HistoryMenu1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HistoryMenu1.setForeground(java.awt.Color.white);
        HistoryMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HistoryMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_order_history_80px.png"))); // NOI18N
        HistoryMenu1.setText("History");
        HistoryMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HistoryMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryMenu1MouseClicked(evt);
            }
        });

        TreatmentMenu1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TreatmentMenu1.setForeground(java.awt.Color.white);
        TreatmentMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TreatmentMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cleansing_50px.png"))); // NOI18N
        TreatmentMenu1.setText("Treatment");
        TreatmentMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TreatmentMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreatmentMenu1MouseClicked(evt);
            }
        });

        StylistMenu1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        StylistMenu1.setForeground(java.awt.Color.white);
        StylistMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StylistMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_beard_50px.png"))); // NOI18N
        StylistMenu1.setText("Stylist");
        StylistMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StylistMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StylistMenu1MouseClicked(evt);
            }
        });

        BookingMenu1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BookingMenu1.setForeground(java.awt.Color.white);
        BookingMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookingMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_ticket_50px.png"))); // NOI18N
        BookingMenu1.setText("Booking");
        BookingMenu1.setToolTipText("");
        BookingMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookingMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMenu1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SidePanel1Layout = new javax.swing.GroupLayout(SidePanel1);
        SidePanel1.setLayout(SidePanel1Layout);
        SidePanel1Layout.setHorizontalGroup(
            SidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanel1Layout.createSequentialGroup()
                .addGroup(SidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BookingMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Homemenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(HistoryMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TreatmentMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StylistMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SidePanel1Layout.setVerticalGroup(
            SidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Homemenu1)
                .addGap(50, 50, 50)
                .addComponent(BookingMenu1)
                .addGap(58, 58, 58)
                .addComponent(StylistMenu1)
                .addGap(55, 55, 55)
                .addComponent(TreatmentMenu1)
                .addGap(51, 51, 51)
                .addComponent(HistoryMenu1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel.setBackground(new java.awt.Color(27, 26, 23));

        UserButton.setForeground(java.awt.Color.white);
        UserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_account_30px.png"))); // NOI18N
        UserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_barbershop_100px.png"))); // NOI18N
        jLabel2.setText("BarberBross");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LogOutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Logout_50px.png"))); // NOI18N
        LogOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutButton)
                .addGap(18, 18, 18)
                .addComponent(UserButton)
                .addGap(26, 26, 26))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LogOutButton)
                            .addComponent(UserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(230, 213, 184));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Your Hairstylist");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barber2.jpg"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barber3.jpg"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name     : Jamaludin bin Isnaeni");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Age         : 37");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Name : Komar bin Tamami");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Age     : 42");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Email      : Jabisnaeni@gmail.com");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Mastery : All Hairstyle");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Email      : Komit4646@gmail.com");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Mastery : All Hairstyle and treatment");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))))))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)))
                .addGap(75, 75, 75)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)))
                .addGap(286, 286, 286)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SidePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Homemenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Homemenu1MouseClicked
        // TODO add your handling code here:
        Home homePage = new Home();
        homePage.show();

        dispose();
    }//GEN-LAST:event_Homemenu1MouseClicked

    private void HistoryMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMenu1MouseClicked
        // TODO add your handling code here:
        History historyPage = new History();
        historyPage.show();

        dispose();
    }//GEN-LAST:event_HistoryMenu1MouseClicked

    private void TreatmentMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreatmentMenu1MouseClicked
        // TODO add your handling code here:
        Treatment treatmentPage = new Treatment();
        treatmentPage.show();

        dispose();
    }//GEN-LAST:event_TreatmentMenu1MouseClicked

    private void StylistMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StylistMenu1MouseClicked
        // TODO add your handling code here:
        InterfaceStylist stylistPage = new InterfaceStylist();
        stylistPage.show();

        dispose();
    }//GEN-LAST:event_StylistMenu1MouseClicked

    private void BookingMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMenu1MouseClicked
        // TODO add your handling code here:
        Interface bookingPage = new Interface();
        bookingPage.show();
        
        dispose();
    }//GEN-LAST:event_BookingMenu1MouseClicked

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You've been log out!");

        Login loginPage = new Login();
        loginPage.show();

        dispose();
    }//GEN-LAST:event_LogOutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceStylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceStylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceStylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceStylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceStylist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookingMenu1;
    private javax.swing.JLabel HistoryMenu1;
    private javax.swing.JLabel Homemenu1;
    private javax.swing.JLabel LogOutButton;
    private javax.swing.JPanel SidePanel1;
    private javax.swing.JLabel StylistMenu1;
    private javax.swing.JLabel TreatmentMenu1;
    private javax.swing.JLabel UserButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
